### PR TITLE
Add grafana archive

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <swiftgist@gmail.com>

### CODE REVIEW

**Review by p-se — APPROVED** [review]
lgtm

**Review by mgfritch — APPROVED** [review]
https://github.com/ceph/ceph/pull/33746 needs to merge first to avoid breaking the existing tests.

otherwise, lgtm!

**Comment by sebastian-philipp** [comment]
ceph/ceph#33746  was merged. are we good to go here?

**Comment by sebastian-philipp** [comment]
blocked by https://github.com/ceph/ceph/pull/34619

**Pull request merged**
