### PR TITLE
Add prometheus.tgz

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <swiftgist@gmail.com>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
That's prometheus, as deployed by deepsea, right? then what about renaming this to `deepsea-prometheus`?

**Review by mgfritch — COMMENTED** [review]
> That's prometheus, as deployed by deepsea, right? then what about renaming this to `deepsea-prometheus`?

hmm yeah, there is a fair amount of SUSE specific config items in the `prometheus.yml`  .. maybe this conf should be updated to be more generic?

**Comment by swiftgist** [comment]
I replaced the prometheus.yml with the generic one.  This has nothing to do with deepsea.

**Review by mgfritch — APPROVED** [review]
lgtm

**Pull request merged**
