### PR TITLE
Add alertmanager archive

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <swiftgist@gmail.com>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
ping @mgfritch

**Review by mgfritch — APPROVED** [review]
Generally looks ok from an adoption test standpoint.

One discrepancy, the  yaml config in this corpus uses a web-hook `http://127.0.0.1:5001/`, whereas cephadm in Octopus uses `<dashboard_url>/api/prometheus_receiver` ... @p-se  any thoughts, will this be an issue for a successful adoption?

**Comment by sebastian-philipp** [comment]
right now, if we add this, 

https://github.com/ceph/ceph/blob/c32350ed98bea42d8c6911bcc5b26e1231c69c0a/qa/workunits/cephadm/test_adoption.sh#L53-L56

all branches will directly checkout this new commit. IMO we should checkout a specific commit in `test_adoption` first, and then have a separate PR to update the commit it. cc @liewegas

**Comment by liewegas** [comment]
What about having that checkout a branch instead of a commit? taht way it's master in master, octopus in octopus branch, and we don't have to coordinate the changes to both repos like we do with submodules?  Seems like less work that way

**Comment by sebastian-philipp** [comment]
but still, we need to do a QA run with this blob *before* merging this.

**Comment by p-se** [comment]
tbh, I've no idea where the 5001 is coming from, but if it results in a configuration which looks like `<dashboard_url>/api/prometheus_receiver`, it'll be fine

**Comment by swiftgist** [comment]
The alertmanager.yml came from the upstream alertmanager-0.20.0.linux-amd64.  That is where the port 5001 is coming from.

**Comment by sebastian-philipp** [comment]
blocked by https://github.com/ceph/ceph/pull/34619

**Pull request merged**
